"""Draft a complaint for the National Cyber Crime Reporting Portal.

Dadi never files anything herself: the user reviews this draft and submits it
at cybercrime.gov.in (or calls 1930). Suspected fraud calls that caused no loss
can also be reported on Sanchar Saathi's Chakshu portal.
"""

from __future__ import annotations

from datetime import datetime

SCAM_LABEL = {
    "digital_arrest": "Impersonation of law enforcement ('digital arrest')",
    "kyc_bank": "Bank / KYC impersonation fraud",
    "courier_parcel": "Courier / customs parcel fraud",
    "task_job": "Online task / part-time job fraud",
    "investment": "Investment / trading fraud",
    "electricity_bill": "Utility bill disconnection fraud",
    "lottery_prize": "Lottery / prize fraud",
}
TACTIC_LABEL = {
    "authority": "impersonated an authority", "urgency": "created false urgency", "fear": "used threats and fear",
    "secrecy": "demanded secrecy / isolation", "payment_request": "demanded money transfer",
    "credential_request": "asked for OTP / PIN / remote access", "reward_lure": "offered a fake reward",
}


def draft(record: dict, ring: dict | None = None) -> str:
    intel = record.get("intel", {})
    started = datetime.fromisoformat(record["started_at"]).strftime("%d %b %Y, %I:%M %p")
    scam = SCAM_LABEL.get(record.get("scam_type") or "", "Suspected fraud call")
    tactics = [TACTIC_LABEL[t] for t in record.get("tactics", []) if t in TACTIC_LABEL]

    def lines(key: str) -> str:
        vals = intel.get(key, [])
        return "\n".join(f"  - {v}" for v in vals) if vals else "  - (none captured)"

    caller_quotes = [h["text"] for h in record.get("transcript", []) if h["role"] == "caller"][:6]
    quotes = "\n".join(f'  > "{q}"' for q in caller_quotes)
    officer = ", ".join(intel.get("officer_names", [])) or "not stated"
    claimed = ", ".join(intel.get("authorities", [])) or "not stated"

    ring_text = ""
    if ring:
        ring_text = (f"\n## Linked calls\nThis caller's identifiers also appear in {ring['n_calls'] - 1} other "
                     f"call(s) captured by Dadi (ring {ring['ring_id']}). Shared identifiers:\n"
                     + "\n".join(f"  - {s}" for s in ring["shared_identifiers"]) + "\n")

    return f"""# DRAFT: Cyber fraud complaint (review before submitting)

**Submit at:** https://cybercrime.gov.in → "Report Other Cyber Crime", or call **1930**.
No money was lost, so you can also report the number on Sanchar Saathi → **Chakshu**.

## Incident
- Category: Online Financial Fraud → {scam}
- Date & time of call: {started}
- Call duration (scammer kept engaged by Dadi): {record.get('wasted_s', 0) // 60} min {record.get('wasted_s', 0) % 60} s
- Money lost: **None** (call answered by the Dadi AI assistant)

## Suspect details
- Claimed to be: {claimed}
- Name(s) used: {officer}
- Phone numbers mentioned:
{lines('phones')}
- UPI IDs given for payment:
{lines('upi_ids')}
- Bank account numbers:
{lines('accounts')}
- IFSC codes:
{lines('ifsc')}
- Amounts demanded:
{lines('amounts')}

## Description
The caller {', '.join(tactics) or 'attempted to defraud me'}. They asked for payment to the
identifiers listed above. No payment or personal information was shared.

Excerpts from the caller (automatic transcript):
{quotes}
{ring_text}
---
_Generated by Dadi from call {record['id']}. Automatic transcripts can contain errors: please check every identifier._
"""
